server:
  port: 8888

logging:
  level:
    root: WARN
    #org.springframework.boot: DEBUG
    com.github.zacscoding: DEBUG

spring:
  cloud:
    config:
      uri:
        - http://localhost:8888/config-server
      server:
        prefix: /config-server
        git:
          # default 0, 매 요청마다 fetch
          # 단위는 Second 이며 (refresh > 0 && (now() - lastRefresh) < (refreshRate * 1000) 면 fetch 하지 않음
          refresh-rate: 0
          uri: file://${user.home}/config-repo