DROP TABLE IF EXISTS foo;

CREATE TABLE IF NOT EXISTS foo (
    foo_id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY ,
    first VARCHAR(45) NOT NULL ,
    second VARCHAR(45) NOT NULL ,
    third VARCHAR(45) NOT NULL ,
    message VARCHAR(1024) NOT NULL
);